import { jsPDF } from 'jspdf';

export const downloadReport = (analysis, fileName = 'Resume_Analysis_Report') => {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  let y = 20;

  const addText = (text, x, fontSize = 11, bold = false, color = [30, 30, 30]) => {
    doc.setFontSize(fontSize);
    doc.setFont('helvetica', bold ? 'bold' : 'normal');
    doc.setTextColor(...color);
    const lines = doc.splitTextToSize(text, pageWidth - x - 20);
    doc.text(lines, x, y);
    y += lines.length * (fontSize * 0.45) + 3;
  };

  const checkPage = () => {
    if (y > 270) { doc.addPage(); y = 20; }
  };

  // Header
  doc.setFillColor(79, 70, 229);
  doc.rect(0, 0, pageWidth, 35, 'F');
  doc.setFontSize(20);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(255, 255, 255);
  doc.text('ResumeAI — Analysis Report', 15, 22);
  y = 45;

  // ATS Score
  addText(`ATS Score: ${analysis.atsScore}/100`, 15, 16, true, [79, 70, 229]);
  addText(`Verdict: ${analysis.verdict}`, 15, 13, true);
  addText(`Summary: ${analysis.summary}`, 15, 11);
  y += 5;

  // Score Breakdown
  checkPage();
  addText('Score Breakdown', 15, 14, true, [79, 70, 229]);
  const breakdown = analysis.scoreBreakdown;
  addText(`• Keyword Match: ${breakdown.keywordMatch}/100`, 20, 11);
  addText(`• Relevance: ${breakdown.relevance}/100`, 20, 11);
  addText(`• Formatting: ${breakdown.formatting}/100`, 20, 11);
  addText(`• Experience: ${breakdown.experience}/100`, 20, 11);
  y += 5;

  // Keywords Found
  checkPage();
  addText('Keywords Found', 15, 14, true, [22, 163, 74]);
  if (analysis.foundKeywords?.length > 0) {
    addText(analysis.foundKeywords.join(', '), 20, 10);
  }
  y += 3;

  // Keywords Missing
  checkPage();
  addText('Missing Keywords', 15, 14, true, [220, 38, 38]);
  if (analysis.missingKeywords?.length > 0) {
    addText(analysis.missingKeywords.join(', '), 20, 10);
  }
  y += 5;

  // Strengths
  checkPage();
  addText('Strengths', 15, 14, true, [79, 70, 229]);
  analysis.strengths?.forEach((s) => {
    checkPage();
    addText(`✓ ${s}`, 20, 11);
  });
  y += 5;

  // Improvements
  checkPage();
  addText('Improvements Needed', 15, 14, true, [220, 38, 38]);
  analysis.improvements?.forEach((imp) => {
    checkPage();
    addText(`[${imp.priority.toUpperCase()}] ${imp.section}: ${imp.issue}`, 20, 11, true);
    addText(`→ ${imp.fix}`, 25, 10);
    y += 2;
  });
  y += 5;

  // Tips
  checkPage();
  addText('Pro Tips', 15, 14, true, [79, 70, 229]);
  analysis.tips?.forEach((t) => {
    checkPage();
    addText(`${t.category}: ${t.tip}`, 20, 11);
    y += 2;
  });

  // Footer
  const pageCount = doc.internal.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(9);
    doc.setTextColor(150, 150, 150);
    doc.text(`Generated by ResumeAI — Page ${i} of ${pageCount}`, 15, 290);
  }

  doc.save(`${fileName}.pdf`);
};
